#!/bin/bash

# This script will be executed on the host before building Docker images.

echo 'Generating .devcontainer/.env'

cat <<EOF > .devcontainer/.env
# This file was generated by initializeCommand.
COMPOSE_USER_ID=$(id -u)
COMPOSE_GROUP_ID=$(id -g)
DOCKER_GROUP_ID=$(getent group docker | cut -d: -f3)
EOF
