#!/bin/bash

# This script will be executed on the host before building Docker images.

cat <<EOF > .devcontainer/.env
# This file was generated by initializeCommand.
USER_UID=$(id -u)
USER_GID=$(id -g)
DOCKER_GID=$(getent group docker | cut -d: -f3)
EOF
